#!/bin/bash

# ============================================================
# FIGMA SLIDES 图片导出助手
# ============================================================
# 文件: https://www.figma.com/slides/VhGLPdQrI8yGPSgo0emmyz
# 输出: /Users/aa123/Documents/presentation skills/MAI Design Skill/asset/Images
# ============================================================

OUTPUT_DIR="/Users/aa123/Documents/presentation skills/MAI Design Skill/asset/Images"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         FIGMA SLIDES 图片导出指南                           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 输出文件夹: $OUTPUT_DIR"
echo ""
echo "⚠️  注意: Figma Slides 文件不支持 REST API 直接导出"
echo ""

# 创建文件夹
mkdir -p "$OUTPUT_DIR"

echo "✅ 文件夹已创建并准备就绪"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 手动导出步骤（推荐）："
echo ""
echo "1️⃣  在浏览器打开文件"
echo "   https://www.figma.com/slides/VhGLPdQrI8yGPSgo0emmyz"
echo ""
echo "2️⃣  在 Figma 中："
echo "   • 点击左侧面板选择幻灯片/元素"
echo "   • 可以多选 (Cmd/Ctrl + 点击)"
echo ""
echo "3️⃣  导出方式A - 单个元素："
echo "   • 选中元素"
echo "   • 右键 → Export [元素名]"
echo "   • 选择 PNG 格式，2x 缩放"
echo "   • 保存到: $OUTPUT_DIR"
echo ""
echo "4️⃣  导出方式B - 整页截图："
echo "   • 选中整个幻灯片"
echo "   • 右侧面板 → Export 部分"
echo "   • 添加导出设置: PNG, 2x"
echo "   • 点击 Export"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 建议导出的关键资源："
echo ""
echo "📄 Slides/Frames:"
echo "   • Cover 页面"
echo "   • 所有幻灯片页面"
echo "   • 模板布局示例"
echo ""
echo "🎨 视觉元素:"
echo "   • Logo 和品牌图标"
echo "   • 背景图案"
echo "   • 装饰性插图"
echo ""
echo "🧩 组件:"
echo "   • Badge 组件"
echo "   • Label 组件"
echo "   • Card 组件示例"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 推荐文件命名规则："
echo ""
echo "   slide_01_cover.png"
echo "   slide_02_title.png"
echo "   component_badge_yellow.png"
echo "   icon_copilot_100px.png"
echo "   bg_warm_beige.png"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 快速打开："
echo ""

# Open URLs
echo "   正在打开 Figma 文件..."
open "https://www.figma.com/slides/VhGLPdQrI8yGPSgo0emmyz"

sleep 1

echo "   正在打开输出文件夹..."
open "$OUTPUT_DIR"

echo ""
echo "✅ Figma 文件和输出文件夹已打开！"
echo ""
echo "现在您可以在 Figma 中选择元素并导出到已打开的文件夹中。"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  提示: 导出完成后，运行 'ls -la \"$OUTPUT_DIR\"'  ║"
echo "║        查看已导出的文件                                      ║"
echo "╚══════════════════════════════════════════════════════════════╝"
